GET http://localhost:500/users

###
Get http://localhost:500/users/60d687242c004d145f233292

###
Post http://localhost:500/users
Content-Type: application/json

{
    "name":"Tafhim Hasan",
    "email":"tafhim@gmail.com"
}

###
PATCH http://localhost:500/users/60d68c72a7868f150070d8cf
Content-Type: application/json

{
    "name":"New Tafhim Hasan",
    "email":"neweamil@gmail.com"
}

###
DELETE http://localhost:500/users/60d68c72a7868f150070d8cf
